apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- examples/spring-rest-jpa.yaml
# Uncomment for Google Managed Prometheus metrics scraping
#- examples/spring-rest-jpa-gmp.yaml

namespace: demo

configMapGenerator:
- name: spring-rest-jpa-config
  files:
  - application.yaml
