apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: spring-rest-jpa
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-rest-jpa
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 5s
