apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-rest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: go-rest
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-rest
    spec:
      serviceAccountName: go-rest
      containers:
      - name: go-rest
        image: ghcr.io/mikouaj/go-rest:latest
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: go-rest
spec:
  selector:
    app.kubernetes.io/name: go-rest
  ports:
  - port: 8080
    targetPort: http
