apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-rest-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-rest-client-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: go-rest-client-one
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-rest-client-one
    spec:
      serviceAccountName: go-rest-client
      containers:
      - name: go-rest-client
        image: ghcr.io/mikouaj/go-rest-client:latest
        env:
        - name: GO_REST_CLIENT_APP_NAME
          value: service-one
        - name: GO_REST_CLIENT_DATA_URL
          value: http://service-two.demo.svc.cluster.local:8080/data
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: service-one
spec:
  selector:
    app.kubernetes.io/name: go-rest-client-one
  ports:
  - port: 8080
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-rest-client-two
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: go-rest-client-two
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-rest-client-two
    spec:
      serviceAccountName: go-rest-client
      containers:
      - name: go-rest-client
        image: ghcr.io/mikouaj/go-rest-client:latest
        env:
        - name: GO_REST_CLIENT_APP_NAME
          value: service-two
        - name: GO_REST_CLIENT_DATA_URL
          value: http://service-three.demo.svc.cluster.local:8080/data
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: service-two
spec:
  selector:
    app.kubernetes.io/name: go-rest-client-two
  ports:
  - port: 8080
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-rest-client-three
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: go-rest-client-three
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-rest-client-three
    spec:
      serviceAccountName: go-rest-client
      containers:
      - name: go-rest-client
        image: ghcr.io/mikouaj/go-rest-client:latest
        env:
        - name: GO_REST_CLIENT_APP_NAME
          value: service-three
        - name: GO_REST_CLIENT_DATA_URL
          value: https://api.github.com/orgs/google
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: service-three
spec:
  selector:
    app.kubernetes.io/name: go-rest-client-three
  ports:
  - port: 8080
    targetPort: http
