name: Go Rest Cloud Storage Build
on:
  push:
    branches:
      - main
    paths:
      - 'go-rest-cloud-storage/**'
  pull_request:
    branches:
      - main
    paths:
      - 'go-rest-cloud-storage/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./go-rest-cloud-storage
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: Get dependencies
        run: go mod download
      - name: Build
        run: make build
      - name: Test
        run: make test
      - name: Lint
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2023.1.2"
          install-go: false
          working-directory: ./go-rest-cloud-storage
