name: Spring Rest JPA Build
on:
  push:
    branches:
      - main
    paths:
      - 'spring-rest-jpa/**'
  pull_request:
    branches:
      - main
    paths:
      - 'spring-rest-jpa/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./spring-rest-jpa
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Build
        run: mvn --batch-mode --update-snapshots package
    